# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mmaria-d <mmaria-d@student.42lisboa.com    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/09/06 11:51:09 by mmaria-d          #+#    #+#              #
#    Updated: 2024/09/06 11:51:57 by mmaria-d         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# Makefile to compile the threadpool into a library
# The end user will be responsible for linking pthread (-lpthread) when compiling
# the threadpoll into their own projects