# include "DefaultConfig.hpp"

DefaultConfig::DefaultConfig() :
	max_connections			(DEFAULTCONF_PROGRAM_MAX_CONNECTIONS),
	max_concurrent_cgi		(DEFAULTCONF_PROGRAM_MAX_CGI),
	max_cgi_backlog			(DEFAULTCONF_PROGRAM_CGI_MAXBACKLOG),
	max_workers				(DEFAULTCONF_PROGRAM_MAX_WORKERS),
	serverRoot				(DEFAULTCONF_BLOCK_ROOT),
	maxClientBodySize		(DEFAULTCONF_BLOCK_HTTP_MAX_CLIENT_BODY_SIZE),
	maxClientHeaderSize		(DEFAULTCONF_BLOCK_HTTP_MAX_CLIENT_HEADER_SIZE),
	IPListen				(DEFAULTCONF_BLOCK_IP_LISTEN),
	http400Path				(DEFAULTCONF_BLOCK_ERROR_400_PAGE),
	http404Path				(DEFAULTCONF_BLOCK_ERROR_404_PAGE),
	autoIndex				(DEFAULTCONF_LOCATION_AUTOINDEX),
	methods					(DEFAULTCONF_LOCATION_METHODS),
	type					(DEFAULTCONF_LOCATION_TYPE)
{

}