
#include <cstddef> // size_t

const char potato_text[] = "Potatoes: A Versatile and Nutritious Staple\n"
"The potato (Solanum tuberosum) is one of the most widely consumed and cultivated crops in the world. \n"
"Originally domesticated in the Andean region of South America over 7,000 years ago, potatoes have since \n"
"spread across the globe, becoming a dietary staple in many cultures. Their resilience, nutritional value, \n"
"and versatility in cooking make them one of the most important agricultural products today.\n"
"\n\n"
"Origins and Cultivation"
"Potatoes were first cultivated by indigenous peoples in present-day Peru and Bolivia. Spanish explorers \n"
"brought them to Europe in the 16th century, where they quickly gained popularity due to their ability to \n"
"grow in diverse climates. By the 18th century, potatoes had become a key food source in many European \n"
"countries, particularly in Ireland, where they became a staple crop. However, reliance on a single variety\n \n"
"led to the devastating Irish Potato Famine (1845–1852) when a fungal disease known as potato blight wiped "
"out crops, causing mass starvation."
"\n\n"
"Today, potatoes are grown in over 150 countries. They thrive in cool climates with well-drained soil and \n"
"require relatively little maintenance compared to other crops. China, India, Russia, and the United States \n"
"are among the largest producers, supplying both local and global markets.\n"
"\n\n"
"Nutritional Benefits"
"Despite misconceptions that potatoes are unhealthy, they are actually packed with essential nutrients. \n"
"A medium-sized potato provides a good source of vitamin C, vitamin B6, potassium, and fiber—especially \n"
"when eaten with the skin. They are naturally fat-free and contain complex carbohydrates, which provide \n"
"long-lasting energy. While deep-fried preparations like French fries and potato chips add unhealthy \n"
"fats and excess sodium, boiled, baked, or roasted potatoes can be a nutritious addition to any diet.\n"
"\n\n"
"Varieties of Potatoes"
"There are thousands of potato varieties, each suited for different culinary uses. Broadly, they can be \n"
"categorized into three types:\n"
"\n\n"
"Starchy Potatoes – These have a high starch content and a dry, fluffy texture, making them ideal for \n"
"baking, frying, and mashing. Russet potatoes are the most well-known example.\n"
"Waxy Potatoes – These have a lower starch content and hold their shape well when cooked, making them \n"
"perfect for boiling, roasting, and using in salads. Red potatoes and fingerlings fall into this category.\n"
"All-Purpose Potatoes – These strike a balance between starchy and waxy, meaning they can be used in a \n"
"variety of dishes. Yukon Gold potatoes are a popular all-purpose variety.\n"
"Culinary Uses"
"Potatoes are incredibly versatile in the kitchen and are used in cuisines around the world. Some of\n" 
"the most famous potato-based dishes include mashed potatoes, French fries, potato salad, gnocchi, latkes, \n"
"and shepherd’s pie. In addition to savory dishes, potatoes can also be used in bread and even desserts, such as potato-based doughnuts.\n"
"\n\n"
"Conclusion"
"The humble potato is a vital food crop with a fascinating history and countless culinary applications. \n"
"Whether boiled, baked, mashed, or fried, potatoes continue to be a beloved and indispensable ingredient \n"
"in kitchens worldwide. Their nutritional benefits, affordability, and adaptability ensure that they will \n"
"remain a dietary staple for generations to come.\n";

const char orange_text[] = "Oranges: A Juicy and Nutritious Citrus Fruit\n"
"\n\n"
"The orange (Citrus × sinensis) is one of the most popular and widely cultivated \n"
"fruits in the world. Known for its refreshing taste, vibrant color, and high \n"
"vitamin C content, oranges are enjoyed fresh, juiced, and in a variety of culinary \n"
"applications. Originating in Asia, oranges have spread across the globe, becoming \n"
"a staple in many diets due to their health benefits and versatility.\n"
"\n\n"
"Origins and Cultivation"
"Oranges are believed to have originated in southern China, northeastern India, \n"
"and Southeast Asia thousands of years ago. They were introduced to the Mediterranean \n"
"region around 200 BCE and later brought to the Americas by Spanish explorers in the \n"
"15th and 16th centuries. Today, oranges are grown in warm, subtropical, and tropical \n"
"climates, with Brazil, the United States, China, and India being among the largest \n"
"producers."
"\n\n"
"Orange trees thrive in well-drained, slightly acidic soil with plenty of sunlight. \n"
"They are evergreen, meaning they keep their leaves year-round, and can produce fruit \n"
"for several decades. The fruit typically takes several months to ripen, turning from \n"
"green to bright orange as it matures, although some varieties remain green even when \n"
"fully ripe.\n"
"\n\n"
"Nutritional Benefits\n"
"Oranges are well known for their high vitamin C content, which supports immune \n"
"function and acts as a powerful antioxidant. They also provide dietary fiber, potassium,\n"
" folate, and other essential vitamins and minerals. Oranges are naturally low in calories \n"
"and contain beneficial plant compounds such as flavonoids and carotenoids, which have been\n"
" linked to heart health and reduced inflammation.\n"
"\n\n"
"Consuming oranges regularly can help improve digestion, support healthy skin, and \n"
"lower the risk of chronic diseases such as heart disease and high blood pressure. \n"
"Orange juice is a popular way to enjoy the fruit’s nutrients, but eating whole oranges\n"
" is even healthier due to the fiber content found in the pulp.\n"
"\n\n"
"Varieties of Oranges\n"
"There are many different varieties of oranges, each with unique characteristics \n"
"suited for different purposes. The main types include:\n"
"\n\n"
"Sweet Oranges – The most commonly consumed variety, used for fresh eating and juicing.\n"
" Examples include Navel oranges, Valencia oranges, and Blood oranges.\n"
"Bitter Oranges – These are less commonly eaten fresh due to their tart flavor but are \n"
"used to make marmalades, liqueurs (such as Grand Marnier), and traditional medicines. \n"
"The Seville orange is a well-known example."
"Mandarins and Related Varieties – These include smaller, easy-to-peel citrus fruits \n"
"like tangerines, clementines, and satsumas. They are typically sweeter and less acidic\n"
" than standard oranges.\n"
"Culinary Uses"
"Oranges are used in a wide range of culinary applications. Fresh oranges can be eaten\n"
" on their own, added to fruit salads, or used as a garnish. Orange juice is a breakfast\n"
"  staple, and its zest adds flavor to baked goods, marinades, and sauces. Oranges are \n"
"  also used in savory dishes, pairing well with meats, seafood, and salads. In some \n"
"  cuisines, dried orange peel is incorporated into spice blends and teas.\n"
"\n\n"
"Conclusion"
"Oranges are a delicious and nutritious fruit with a rich history and global appeal. \n"
"Their refreshing taste, health benefits, and versatility make them a favorite among \n"
"people of all ages. Whether eaten fresh, juiced, or used in cooking, oranges continue \n"
"to be a cherished and essential part of a balanced diet.\n";

const size_t orange_text_size = sizeof(orange_text) - 1;
const size_t potato_text_size = sizeof(potato_text) - 1;